export const POPUP = {
    STORE_POPUP: {
        display: true,
        type: "store",
        popupContent: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
        showCloseBtn: true,
        closeBtn: "Hủy",
        showDenyBtn: true,
        denyBtn: "Không",
        confirmBtn: "Có",
    },
    VALIDATE_POPUP: {
        display: true,
        type: "validate",
        popupContent: "",
        showCloseBtn: false,
        closeBtn: "",
        showDenyBtn: false,
        denyBtn: "",
        confirmBtn: "Đóng",
    },
    DELETE_POPUP: {
        display: true,
        type: "delete",
        popupContent: "Bạn có chắc muốn xoá bản ghi này?",
        showCloseBtn: true,
        closeBtn: "Không",
        showDenyBtn: false,
        denyBtn: "",
        confirmBtn: "Có",
    },
    DUPLICATE_POPUP: {
        display: true,
        type: "duplicate",
        popupContent: "Mã nhân viên đã tồn tại trong hệ thống, vui lòng kiểm tra lại.",
        showCloseBtn: false,
        closeBtn: "",
        showDenyBtn: false,
        denyBtn: "",
        confirmBtn: "Đồng ý",
    },
};
